before_install:
    - git submodule update --init --recursive
language: node_js
node_js:
    - "14"
before_script:
    - npm install
script: npm run build
deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: dist/collegues-front
  skip-cleanup: true
  on:
    branch: master
notifications:
  email: false
